/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) right_finger_joint_acados_model_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};

/* right_finger_joint_acados_model_cost_ext_cost_fun_jac:(i0[12],i1[12],i2[0],i3[12])->(o0,o1[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a9;
  a0=5.0000000000000000e-01;
  a1=4.1299999999999998e-01;
  a2=arg[0]? arg[0][0] : 0;
  a3=cos(a2);
  a4=2.2204460492503131e-16;
  a5=arg[0]? arg[0][1] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a5=sin(a5);
  a8=(a7-a5);
  a9=(a3*a8);
  a2=sin(a2);
  a10=(a4*a5);
  a11=(a2*a10);
  a9=(a9-a11);
  a11=(a1*a9);
  a12=2.6499999999999999e-02;
  a13=(a12*a2);
  a11=(a11-a13);
  a13=1.8850000000000000e-01;
  a14=arg[0]? arg[0][2] : 0;
  a15=cos(a14);
  a16=(a9*a15);
  a17=(a10+a6);
  a18=(a3*a17);
  a19=(a2*a7);
  a18=(a18+a19);
  a14=sin(a14);
  a19=(a18*a14);
  a20=-2.2204460492503131e-16;
  a21=(a20*a3);
  a21=(a21+a2);
  a22=1.2246467991473532e-16;
  a23=(a22*a14);
  a24=(a21*a23);
  a19=(a19+a24);
  a16=(a16+a19);
  a19=(a13*a16);
  a24=-8.0000000000000002e-03;
  a25=-1.2246467991473532e-16;
  a26=(a25*a18);
  a26=(a26+a21);
  a27=(a24*a26);
  a19=(a19-a27);
  a11=(a11+a19);
  a19=2.8500000000000001e-02;
  a27=-1.1102230246251565e-16;
  a28=arg[0]? arg[0][3] : 0;
  a29=cos(a28);
  a30=(a27*a29);
  a31=(a16*a30);
  a32=(a18*a15);
  a33=(a22*a15);
  a34=(a21*a33);
  a32=(a32+a34);
  a34=(a9*a14);
  a32=(a32-a34);
  a34=(a4*a29);
  a35=-9.9999999999999989e-01;
  a28=sin(a28);
  a36=(a35*a28);
  a34=(a34-a36);
  a37=(a32*a34);
  a38=(a35*a29);
  a39=(a27*a28);
  a40=(a38-a39);
  a41=(a26*a40);
  a37=(a37-a41);
  a31=(a31+a37);
  a37=(a19*a31);
  a41=1.0000000000000001e-01;
  a42=9.9999999999999989e-01;
  a43=(a42*a16);
  a44=(a27*a32);
  a43=(a43+a44);
  a44=(a41*a43);
  a37=(a37+a44);
  a11=(a11+a37);
  a37=1.5550000000000000e-01;
  a44=(a16*a39);
  a45=(a4*a28);
  a38=(a38+a45);
  a45=(a32*a38);
  a36=(a30+a36);
  a46=(a26*a36);
  a45=(a45-a46);
  a44=(a44+a45);
  a45=arg[0]? arg[0][4] : 0;
  a46=sin(a45);
  a47=-2.4651903288156619e-32;
  a45=cos(a45);
  a48=(a47*a45);
  a48=(a46+a48);
  a49=(a44*a48);
  a50=(a20*a45);
  a51=(a22*a46);
  a50=(a50-a51);
  a51=(a31*a50);
  a52=(a43*a45);
  a51=(a51+a52);
  a49=(a49+a51);
  a49=(a37*a49);
  a51=-2.7000000000000000e-02;
  a52=(a22*a44);
  a53=(a4*a43);
  a53=(a31+a53);
  a52=(a52+a53);
  a52=(a51*a52);
  a49=(a49+a52);
  a11=(a11+a49);
  a49=arg[3]? arg[3][2] : 0;
  a11=(a11-a49);
  a49=casadi_sq(a11);
  a52=(a12*a3);
  a53=(a2*a8);
  a54=(a3*a10);
  a53=(a53+a54);
  a54=(a1*a53);
  a52=(a52+a54);
  a54=(a53*a15);
  a55=(a20*a2);
  a55=(a55-a3);
  a56=(a55*a23);
  a57=(a3*a7);
  a58=(a2*a17);
  a57=(a57-a58);
  a58=(a57*a14);
  a56=(a56-a58);
  a54=(a54+a56);
  a56=(a13*a54);
  a58=(a25*a57);
  a58=(a58-a55);
  a59=(a24*a58);
  a56=(a56+a59);
  a52=(a52+a56);
  a56=(a54*a30);
  a59=(a55*a33);
  a60=(a57*a15);
  a59=(a59-a60);
  a60=(a53*a14);
  a59=(a59-a60);
  a60=(a59*a34);
  a61=(a58*a40);
  a60=(a60+a61);
  a56=(a56+a60);
  a60=(a19*a56);
  a61=(a42*a54);
  a62=(a27*a59);
  a61=(a61+a62);
  a62=(a41*a61);
  a60=(a60+a62);
  a52=(a52+a60);
  a60=(a54*a39);
  a62=(a59*a38);
  a63=(a58*a36);
  a62=(a62+a63);
  a60=(a60+a62);
  a62=(a60*a48);
  a63=(a56*a50);
  a64=(a61*a45);
  a63=(a63+a64);
  a62=(a62+a63);
  a62=(a37*a62);
  a63=(a22*a60);
  a64=(a4*a61);
  a64=(a56+a64);
  a63=(a63+a64);
  a63=(a51*a63);
  a62=(a62+a63);
  a52=(a52+a62);
  a62=arg[3]? arg[3][3] : 0;
  a52=(a52-a62);
  a62=casadi_sq(a52);
  a49=(a49+a62);
  a62=1.1445200000000000e-01;
  a63=(a6+a10);
  a64=(a1*a63);
  a62=(a62+a64);
  a64=(a63*a15);
  a65=(a8*a14);
  a64=(a64-a65);
  a65=(a13*a64);
  a66=(a25*a8);
  a67=(a24*a66);
  a65=(a65+a67);
  a62=(a62+a65);
  a65=(a64*a30);
  a67=(a66*a40);
  a68=(a63*a14);
  a69=(a8*a15);
  a68=(a68+a69);
  a69=(a68*a34);
  a67=(a67-a69);
  a65=(a65+a67);
  a67=(a19*a65);
  a69=(a42*a64);
  a70=(a27*a68);
  a69=(a69-a70);
  a70=(a41*a69);
  a67=(a67+a70);
  a62=(a62+a67);
  a67=(a64*a39);
  a70=(a66*a36);
  a71=(a68*a38);
  a70=(a70-a71);
  a67=(a67+a70);
  a70=(a67*a48);
  a71=(a65*a50);
  a72=(a69*a45);
  a71=(a71+a72);
  a70=(a70+a71);
  a70=(a37*a70);
  a71=(a22*a67);
  a72=(a4*a69);
  a72=(a65+a72);
  a71=(a71+a72);
  a71=(a51*a71);
  a70=(a70+a71);
  a62=(a62+a70);
  a70=arg[3]? arg[3][4] : 0;
  a62=(a62-a70);
  a70=casadi_sq(a62);
  a49=(a49+a70);
  a70=(a0*a49);
  a71=arg[3]? arg[3][0] : 0;
  a70=(a70*a71);
  a72=(a70*a49);
  a73=arg[1]? arg[1][0] : 0;
  a74=20.;
  a73=(a73/a74);
  a75=casadi_sq(a73);
  a76=arg[1]? arg[1][1] : 0;
  a77=10.;
  a76=(a76/a77);
  a77=casadi_sq(a76);
  a75=(a75+a77);
  a77=arg[1]? arg[1][2] : 0;
  a78=5.;
  a77=(a77/a78);
  a79=casadi_sq(a77);
  a75=(a75+a79);
  a79=arg[1]? arg[1][3] : 0;
  a79=(a79/a74);
  a80=casadi_sq(a79);
  a75=(a75+a80);
  a80=arg[1]? arg[1][4] : 0;
  a80=(a80/a74);
  a81=casadi_sq(a80);
  a75=(a75+a81);
  a81=arg[1]? arg[1][5] : 0;
  a81=(a81/a78);
  a82=casadi_sq(a81);
  a75=(a75+a82);
  a82=arg[1]? arg[1][6] : 0;
  a82=(a82/a78);
  a83=casadi_sq(a82);
  a75=(a75+a83);
  a83=arg[1]? arg[1][7] : 0;
  a83=(a83/a78);
  a84=casadi_sq(a83);
  a75=(a75+a84);
  a84=arg[1]? arg[1][8] : 0;
  a84=(a84/a74);
  a74=casadi_sq(a84);
  a75=(a75+a74);
  a74=arg[1]? arg[1][9] : 0;
  a74=(a74/a78);
  a85=casadi_sq(a74);
  a75=(a75+a85);
  a85=arg[1]? arg[1][10] : 0;
  a85=(a85/a78);
  a86=casadi_sq(a85);
  a75=(a75+a86);
  a86=arg[1]? arg[1][11] : 0;
  a86=(a86/a78);
  a78=casadi_sq(a86);
  a75=(a75+a78);
  a78=(a0*a75);
  a87=arg[3]? arg[3][1] : 0;
  a78=(a78*a87);
  a88=(a78*a75);
  a72=(a72+a88);
  if (res[0]!=0) res[0][0]=a72;
  a72=5.0000000000000003e-02;
  a73=(a73+a73);
  a87=(a87*a75);
  a87=(a0*a87);
  a78=(a78+a87);
  a73=(a73*a78);
  a73=(a72*a73);
  if (res[1]!=0) res[1][0]=a73;
  a76=(a76+a76);
  a76=(a76*a78);
  a76=(a41*a76);
  if (res[1]!=0) res[1][1]=a76;
  a76=2.0000000000000001e-01;
  a77=(a77+a77);
  a77=(a77*a78);
  a77=(a76*a77);
  if (res[1]!=0) res[1][2]=a77;
  a79=(a79+a79);
  a79=(a79*a78);
  a79=(a72*a79);
  if (res[1]!=0) res[1][3]=a79;
  a80=(a80+a80);
  a80=(a80*a78);
  a80=(a72*a80);
  if (res[1]!=0) res[1][4]=a80;
  a81=(a81+a81);
  a81=(a81*a78);
  a81=(a76*a81);
  if (res[1]!=0) res[1][5]=a81;
  a82=(a82+a82);
  a82=(a82*a78);
  a82=(a76*a82);
  if (res[1]!=0) res[1][6]=a82;
  a83=(a83+a83);
  a83=(a83*a78);
  a83=(a76*a83);
  if (res[1]!=0) res[1][7]=a83;
  a84=(a84+a84);
  a84=(a84*a78);
  a72=(a72*a84);
  if (res[1]!=0) res[1][8]=a72;
  a74=(a74+a74);
  a74=(a74*a78);
  a74=(a76*a74);
  if (res[1]!=0) res[1][9]=a74;
  a85=(a85+a85);
  a85=(a85*a78);
  a85=(a76*a85);
  if (res[1]!=0) res[1][10]=a85;
  a86=(a86+a86);
  a86=(a86*a78);
  a76=(a76*a86);
  if (res[1]!=0) res[1][11]=a76;
  a52=(a52+a52);
  a71=(a71*a49);
  a0=(a0*a71);
  a70=(a70+a0);
  a52=(a52*a70);
  a0=(a51*a52);
  a71=(a22*a0);
  a49=(a37*a52);
  a76=(a48*a49);
  a71=(a71+a76);
  a76=(a38*a71);
  a86=(a4*a0);
  a78=(a45*a49);
  a86=(a86+a78);
  a78=(a41*a52);
  a86=(a86+a78);
  a78=(a27*a86);
  a76=(a76+a78);
  a78=(a50*a49);
  a0=(a0+a78);
  a78=(a19*a52);
  a0=(a0+a78);
  a78=(a34*a0);
  a76=(a76+a78);
  a78=(a33*a76);
  a85=(a36*a71);
  a74=(a40*a0);
  a85=(a85+a74);
  a74=(a24*a52);
  a85=(a85+a74);
  a78=(a78-a85);
  a74=(a39*a71);
  a86=(a42*a86);
  a74=(a74+a86);
  a86=(a30*a0);
  a74=(a74+a86);
  a86=(a13*a52);
  a74=(a74+a86);
  a86=(a23*a74);
  a78=(a78+a86);
  a86=(a20*a78);
  a85=(a25*a85);
  a72=(a15*a76);
  a85=(a85-a72);
  a72=(a14*a74);
  a85=(a85-a72);
  a72=(a17*a85);
  a86=(a86-a72);
  a72=(a15*a74);
  a84=(a14*a76);
  a72=(a72-a84);
  a84=(a1*a52);
  a72=(a72+a84);
  a84=(a8*a72);
  a86=(a86+a84);
  a11=(a11+a11);
  a11=(a11*a70);
  a84=(a51*a11);
  a83=(a22*a84);
  a82=(a37*a11);
  a81=(a48*a82);
  a83=(a83+a81);
  a81=(a38*a83);
  a80=(a4*a84);
  a79=(a45*a82);
  a80=(a80+a79);
  a79=(a41*a11);
  a80=(a80+a79);
  a79=(a27*a80);
  a81=(a81+a79);
  a79=(a50*a82);
  a84=(a84+a79);
  a79=(a19*a11);
  a84=(a84+a79);
  a79=(a34*a84);
  a81=(a81+a79);
  a33=(a33*a81);
  a79=(a36*a83);
  a77=(a40*a84);
  a79=(a79+a77);
  a77=(a24*a11);
  a79=(a79+a77);
  a33=(a33-a79);
  a77=(a39*a83);
  a80=(a42*a80);
  a77=(a77+a80);
  a80=(a30*a84);
  a77=(a77+a80);
  a80=(a13*a11);
  a77=(a77+a80);
  a23=(a23*a77);
  a33=(a33+a23);
  a86=(a86+a33);
  a23=(a15*a81);
  a79=(a25*a79);
  a23=(a23-a79);
  a79=(a14*a77);
  a23=(a23+a79);
  a79=(a7*a23);
  a86=(a86+a79);
  a79=(a12*a11);
  a86=(a86-a79);
  a79=(a15*a77);
  a80=(a14*a81);
  a79=(a79-a80);
  a11=(a1*a11);
  a79=(a79+a11);
  a11=(a10*a79);
  a86=(a86-a11);
  a86=(a3*a86);
  a7=(a7*a85);
  a7=(a7-a78);
  a10=(a10*a72);
  a7=(a7+a10);
  a12=(a12*a52);
  a7=(a7+a12);
  a33=(a20*a33);
  a7=(a7+a33);
  a17=(a17*a23);
  a7=(a7+a17);
  a17=(a8*a79);
  a7=(a7+a17);
  a7=(a2*a7);
  a86=(a86-a7);
  if (res[1]!=0) res[1][12]=a86;
  a62=(a62+a62);
  a62=(a62*a70);
  a51=(a51*a62);
  a70=(a22*a51);
  a37=(a37*a62);
  a48=(a48*a37);
  a70=(a70+a48);
  a39=(a39*a70);
  a48=(a4*a51);
  a86=(a45*a37);
  a48=(a48+a86);
  a41=(a41*a62);
  a48=(a48+a41);
  a42=(a42*a48);
  a39=(a39+a42);
  a50=(a50*a37);
  a51=(a51+a50);
  a19=(a19*a62);
  a51=(a51+a19);
  a30=(a30*a51);
  a39=(a39+a30);
  a13=(a13*a62);
  a39=(a39+a13);
  a13=(a15*a39);
  a38=(a38*a70);
  a48=(a27*a48);
  a38=(a38+a48);
  a34=(a34*a51);
  a38=(a38+a34);
  a34=(a14*a38);
  a13=(a13-a34);
  a1=(a1*a62);
  a13=(a13+a1);
  a1=(a4*a13);
  a36=(a36*a70);
  a40=(a40*a51);
  a36=(a36+a40);
  a24=(a24*a62);
  a36=(a36+a24);
  a25=(a25*a36);
  a36=(a15*a38);
  a25=(a25-a36);
  a36=(a14*a39);
  a25=(a25-a36);
  a1=(a1-a25);
  a36=(a3*a23);
  a24=(a2*a85);
  a36=(a36-a24);
  a24=(a4*a36);
  a1=(a1+a24);
  a24=(a3*a72);
  a62=(a2*a79);
  a24=(a24-a62);
  a24=(a4*a24);
  a1=(a1+a24);
  a72=(a2*a72);
  a79=(a3*a79);
  a72=(a72+a79);
  a1=(a1-a72);
  a6=(a6*a1);
  a25=(a4*a25);
  a25=(a25+a13);
  a3=(a3*a85);
  a2=(a2*a23);
  a3=(a3+a2);
  a3=(a4*a3);
  a25=(a25+a3);
  a25=(a25+a36);
  a72=(a4*a72);
  a25=(a25+a72);
  a5=(a5*a25);
  a6=(a6-a5);
  if (res[1]!=0) res[1][13]=a6;
  a6=(a55*a74);
  a5=(a21*a77);
  a6=(a6+a5);
  a6=(a22*a6);
  a5=(a63*a38);
  a25=(a8*a39);
  a5=(a5+a25);
  a25=(a53*a76);
  a5=(a5+a25);
  a25=(a57*a74);
  a5=(a5+a25);
  a25=(a9*a81);
  a5=(a5+a25);
  a6=(a6-a5);
  a5=(a18*a77);
  a6=(a6+a5);
  a15=(a15*a6);
  a63=(a63*a39);
  a8=(a8*a38);
  a63=(a63-a8);
  a57=(a57*a76);
  a63=(a63-a57);
  a53=(a53*a74);
  a63=(a63+a53);
  a55=(a55*a76);
  a21=(a21*a81);
  a55=(a55+a21);
  a55=(a22*a55);
  a63=(a63+a55);
  a18=(a18*a81);
  a63=(a63+a18);
  a9=(a9*a77);
  a63=(a63+a9);
  a14=(a14*a63);
  a15=(a15-a14);
  if (res[1]!=0) res[1][14]=a15;
  a15=(a66*a70);
  a14=(a58*a71);
  a15=(a15+a14);
  a14=(a26*a83);
  a15=(a15-a14);
  a14=(a35*a15);
  a63=(a59*a71);
  a9=(a68*a70);
  a63=(a63-a9);
  a9=(a32*a83);
  a63=(a63+a9);
  a9=(a4*a63);
  a14=(a14+a9);
  a70=(a64*a70);
  a71=(a54*a71);
  a70=(a70+a71);
  a83=(a16*a83);
  a70=(a70+a83);
  a70=(a27*a70);
  a14=(a14+a70);
  a66=(a66*a51);
  a58=(a58*a0);
  a66=(a66+a58);
  a26=(a26*a84);
  a66=(a66-a26);
  a26=(a27*a66);
  a14=(a14-a26);
  a59=(a59*a0);
  a68=(a68*a51);
  a59=(a59-a68);
  a32=(a32*a84);
  a59=(a59+a32);
  a32=(a35*a59);
  a14=(a14-a32);
  a29=(a29*a14);
  a15=(a27*a15);
  a63=(a35*a63);
  a15=(a15+a63);
  a35=(a35*a66);
  a15=(a15+a35);
  a4=(a4*a59);
  a15=(a15+a4);
  a64=(a64*a51);
  a54=(a54*a0);
  a64=(a64+a54);
  a16=(a16*a84);
  a64=(a64+a16);
  a27=(a27*a64);
  a15=(a15+a27);
  a28=(a28*a15);
  a29=(a29-a28);
  if (res[1]!=0) res[1][15]=a29;
  a67=(a67*a37);
  a60=(a60*a49);
  a67=(a67+a60);
  a44=(a44*a82);
  a67=(a67+a44);
  a65=(a65*a37);
  a56=(a56*a49);
  a65=(a65+a56);
  a31=(a31*a82);
  a65=(a65+a31);
  a22=(a22*a65);
  a22=(a67-a22);
  a45=(a45*a22);
  a69=(a69*a37);
  a61=(a61*a49);
  a69=(a69+a61);
  a43=(a43*a82);
  a69=(a69+a43);
  a20=(a20*a65);
  a69=(a69+a20);
  a47=(a47*a67);
  a69=(a69+a47);
  a46=(a46*a69);
  a45=(a45-a46);
  if (res[1]!=0) res[1][16]=a45;
  a45=0.;
  if (res[1]!=0) res[1][17]=a45;
  if (res[1]!=0) res[1][18]=a45;
  if (res[1]!=0) res[1][19]=a45;
  if (res[1]!=0) res[1][20]=a45;
  if (res[1]!=0) res[1][21]=a45;
  if (res[1]!=0) res[1][22]=a45;
  if (res[1]!=0) res[1][23]=a45;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int right_finger_joint_acados_model_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int right_finger_joint_acados_model_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real right_finger_joint_acados_model_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_finger_joint_acados_model_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_finger_joint_acados_model_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_finger_joint_acados_model_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_finger_joint_acados_model_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
