/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) right_finger_joint_acados_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* right_finger_joint_acados_model_constr_h_fun:(i0[12],i1[12],i2[0],i3[12])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a5, a6, a7, a8, a9;
  a0=4.1299999999999998e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=cos(a1);
  a3=2.2204460492503131e-16;
  a4=arg[0]? arg[0][1] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a4=sin(a4);
  a7=(a6-a4);
  a8=(a2*a7);
  a1=sin(a1);
  a4=(a3*a4);
  a9=(a1*a4);
  a8=(a8-a9);
  a9=(a0*a8);
  a10=2.6499999999999999e-02;
  a11=(a10*a1);
  a9=(a9-a11);
  a11=1.8850000000000000e-01;
  a12=arg[0]? arg[0][2] : 0;
  a13=cos(a12);
  a14=(a8*a13);
  a15=(a4+a5);
  a16=(a2*a15);
  a17=(a1*a6);
  a16=(a16+a17);
  a12=sin(a12);
  a17=(a16*a12);
  a18=-2.2204460492503131e-16;
  a19=(a18*a2);
  a19=(a19+a1);
  a20=1.2246467991473532e-16;
  a21=(a20*a12);
  a22=(a19*a21);
  a17=(a17+a22);
  a14=(a14+a17);
  a17=(a11*a14);
  a22=-8.0000000000000002e-03;
  a23=-1.2246467991473532e-16;
  a24=(a23*a16);
  a24=(a24+a19);
  a25=(a22*a24);
  a17=(a17-a25);
  a9=(a9+a17);
  a17=2.8500000000000001e-02;
  a25=-1.1102230246251565e-16;
  a26=arg[0]? arg[0][3] : 0;
  a27=cos(a26);
  a28=(a25*a27);
  a29=(a14*a28);
  a16=(a16*a13);
  a30=(a20*a13);
  a19=(a19*a30);
  a16=(a16+a19);
  a8=(a8*a12);
  a16=(a16-a8);
  a8=(a3*a27);
  a19=-9.9999999999999989e-01;
  a26=sin(a26);
  a31=(a19*a26);
  a8=(a8-a31);
  a32=(a16*a8);
  a19=(a19*a27);
  a27=(a25*a26);
  a33=(a19-a27);
  a34=(a24*a33);
  a32=(a32-a34);
  a29=(a29+a32);
  a32=(a17*a29);
  a34=1.0000000000000001e-01;
  a35=9.9999999999999989e-01;
  a36=(a35*a14);
  a37=(a25*a16);
  a36=(a36+a37);
  a37=(a34*a36);
  a32=(a32+a37);
  a9=(a9+a32);
  a32=1.5550000000000000e-01;
  a14=(a14*a27);
  a26=(a3*a26);
  a19=(a19+a26);
  a16=(a16*a19);
  a31=(a28+a31);
  a24=(a24*a31);
  a16=(a16-a24);
  a14=(a14+a16);
  a16=arg[0]? arg[0][4] : 0;
  a24=sin(a16);
  a26=-2.4651903288156619e-32;
  a16=cos(a16);
  a26=(a26*a16);
  a26=(a24+a26);
  a37=(a14*a26);
  a38=(a18*a16);
  a24=(a20*a24);
  a38=(a38-a24);
  a24=(a29*a38);
  a39=(a36*a16);
  a24=(a24+a39);
  a37=(a37+a24);
  a37=(a32*a37);
  a24=-2.7000000000000000e-02;
  a14=(a20*a14);
  a36=(a3*a36);
  a29=(a29+a36);
  a14=(a14+a29);
  a14=(a24*a14);
  a37=(a37+a14);
  a9=(a9+a37);
  a37=2.;
  a9=(a9-a37);
  a9=casadi_sq(a9);
  a10=(a10*a2);
  a37=(a1*a7);
  a14=(a2*a4);
  a37=(a37+a14);
  a14=(a0*a37);
  a10=(a10+a14);
  a14=(a37*a13);
  a18=(a18*a1);
  a18=(a18-a2);
  a21=(a18*a21);
  a2=(a2*a6);
  a1=(a1*a15);
  a2=(a2-a1);
  a1=(a2*a12);
  a21=(a21-a1);
  a14=(a14+a21);
  a21=(a11*a14);
  a1=(a23*a2);
  a1=(a1-a18);
  a15=(a22*a1);
  a21=(a21+a15);
  a10=(a10+a21);
  a21=(a14*a28);
  a18=(a18*a30);
  a2=(a2*a13);
  a18=(a18-a2);
  a37=(a37*a12);
  a18=(a18-a37);
  a37=(a18*a8);
  a2=(a1*a33);
  a37=(a37+a2);
  a21=(a21+a37);
  a37=(a17*a21);
  a2=(a35*a14);
  a30=(a25*a18);
  a2=(a2+a30);
  a30=(a34*a2);
  a37=(a37+a30);
  a10=(a10+a37);
  a14=(a14*a27);
  a18=(a18*a19);
  a1=(a1*a31);
  a18=(a18+a1);
  a14=(a14+a18);
  a18=(a14*a26);
  a1=(a21*a38);
  a37=(a2*a16);
  a1=(a1+a37);
  a18=(a18+a1);
  a18=(a32*a18);
  a14=(a20*a14);
  a2=(a3*a2);
  a21=(a21+a2);
  a14=(a14+a21);
  a14=(a24*a14);
  a18=(a18+a14);
  a10=(a10+a18);
  a18=5.;
  a10=(a10-a18);
  a10=casadi_sq(a10);
  a9=(a9+a10);
  a10=1.1445200000000000e-01;
  a5=(a5+a4);
  a0=(a0*a5);
  a10=(a10+a0);
  a0=(a5*a13);
  a4=(a7*a12);
  a0=(a0-a4);
  a11=(a11*a0);
  a23=(a23*a7);
  a22=(a22*a23);
  a11=(a11+a22);
  a10=(a10+a11);
  a28=(a0*a28);
  a33=(a23*a33);
  a5=(a5*a12);
  a7=(a7*a13);
  a5=(a5+a7);
  a8=(a5*a8);
  a33=(a33-a8);
  a28=(a28+a33);
  a17=(a17*a28);
  a35=(a35*a0);
  a25=(a25*a5);
  a35=(a35-a25);
  a34=(a34*a35);
  a17=(a17+a34);
  a10=(a10+a17);
  a0=(a0*a27);
  a23=(a23*a31);
  a5=(a5*a19);
  a23=(a23-a5);
  a0=(a0+a23);
  a26=(a0*a26);
  a38=(a28*a38);
  a16=(a35*a16);
  a38=(a38+a16);
  a26=(a26+a38);
  a32=(a32*a26);
  a20=(a20*a0);
  a3=(a3*a35);
  a28=(a28+a3);
  a20=(a20+a28);
  a24=(a24*a20);
  a32=(a32+a24);
  a10=(a10+a32);
  a10=casadi_sq(a10);
  a9=(a9+a10);
  a9=sqrt(a9);
  if (res[0]!=0) res[0][0]=a9;
  if (res[0]!=0) res[0][1]=a9;
  if (res[0]!=0) res[0][2]=a9;
  if (res[0]!=0) res[0][3]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void right_finger_joint_acados_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int right_finger_joint_acados_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int right_finger_joint_acados_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real right_finger_joint_acados_model_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_finger_joint_acados_model_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_finger_joint_acados_model_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_finger_joint_acados_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_finger_joint_acados_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_finger_joint_acados_model_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
